version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: usuarios
    ports:
      - "5432:5432"
    volumes:
      - /Users/Administrator/Downloads/mysql:/var/lib/mysql

volumes:
  postgres_data: